export const PROJECTS_DATA = {
  enduravolt: {
    id: "enduravolt",
    title: "EnduraVolt",
    subtitle: "Electric Off-Road Buggy · Regenerative Suspension",
    tag: "Active Project · Co-Founder & Design Lead",
    period: "March 2025 – Present",
    hero: "/images/buggy-render1.png",
    heroStyle: { objectFit: "contain", padding: 40, background: "#0A0A14" },
    summary: "EnduraVolt is a fully electric off-road buggy designed from scratch in SolidWorks, featuring a proprietary regenerative suspension system that converts bump energy into usable electricity — recovering up to 25% of kinetic energy during operation.",
    challenge: "Traditional off-road electric vehicles lose energy through suspension travel. Every bump, dip, and rough terrain feature dissipates kinetic energy as heat. Our challenge was to capture that energy electromagnetically and feed it back to the battery — without compromising suspension performance.",
    approach: "We designed a coil-magnet electromagnetic generator integrated directly into the suspension strut. As the suspension compresses and rebounds, the relative motion between coil and magnet induces a current. Suspension dynamics, electromagnetic behavior, and coil-magnet interactions were all validated through simulation before any physical build.",
    results: [
      "Up to 25% kinetic energy recovery per suspension cycle",
      "Full 4-wheel independent suspension with regenerative struts",
      "Complete SolidWorks assembly with FEA-validated frame",
      "Electromagnetic simulation confirming generator output",
    ],
    tools: ["SolidWorks", "FEA Analysis", "Suspension Dynamics", "Electromagnetic Simulation", "CAD Assembly"],
    images: [
      { src: "/images/buggy-render1.png", caption: "Side profile — full assembly", style: { objectFit: "contain", background: "#0A0A14", padding: 24 } },
      { src: "/images/buggy-render2.png", caption: "Rear view — suspension geometry", style: { objectFit: "contain", background: "#0A0A14", padding: 24 } },
      { src: "/images/buggy-render3.png", caption: "Isometric view", style: { objectFit: "contain", background: "#0A0A14", padding: 24 } },
      { src: "/images/buggy-top.png", caption: "Top view — chassis layout", style: { objectFit: "contain", background: "#0A0A14", padding: 24 } },
      { src: "/images/buggy-solidworks.png", caption: "SolidWorks assembly tree", style: { objectFit: "contain", background: "#0A0A14", padding: 24 } },
    ],
  },
  uav: {
    id: "uav",
    title: "Autonomous Firefighting UAV",
    subtitle: "Wildfire Suppression · VIPP, AUB",
    tag: "Research · VIPP Program · Dr. Bilal Kaddouh",
    period: "January 2025 – Present",
    hero: "/images/aub-lab.jpg",
    heroStyle: { objectFit: "cover" },
    summary: "As part of AUB's Vertically Integrated Projects Program (VIPP), this research project aims to develop an autonomous UAV system capable of detecting and suppressing wildfires in Lebanese terra
